"use strict";
const U="https://bafrksgdcmglahyrppfy.supabase.co";
const K="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhZnJrc2dkY21nbGFoeXJwcGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxMTY4MjQsImV4cCI6MjEwMjY5MjgyNH0.DiWX7vECRUyio5vquCSLMlwhYPaYsummPk0908TYJw8";
const T="martyrs", E="https://raw.githubusercontent.com/forog1980-star/Shohada-app/main/ExcelData/martyrs_master.xlsx";
const B=100,P=1000,D="golzarstone_master_excel_import_done_v2";
const clean=v=>v==null?"":String(v).replace(/\u200c/g," ").replace(/\s+/g," ").trim();
const dig=v=>clean(v).replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d)));
const norm=v=>clean(v).replace(/[يى]/g,"ی").replace(/ك/g,"ک").replace(/[\s_\-–—()\[\]{}:؛;،,.]/g,"").toLowerCase();
const loc=v=>{let s=dig(v);return/^\d+\.0$/.test(s)?s.slice(0,-2):s};
const key=r=>[r.name,r.lastname,r.piece,r.grave_row,r.grave_number].map(clean).join("|");
function show(a,b){document.body.innerHTML=`<div dir="rtl" style="min-height:100vh;display:flex;align-items:center;justify-content:center;background:#f4f7f5;font-family:Tahoma;padding:24px"><div style="width:min(620px,100%);background:white;border-radius:20px;padding:28px;text-align:center"><div style="font-size:38px">${a}</div><div id="mm" style="white-space:pre-line;line-height:2">${b}</div></div></div>`}
function upd(x){let e=document.getElementById("mm");if(e)e.textContent=x}
function app(){let s=document.createElement("script");s.src="app.js?v=20260822-15";s.onload=()=>window.__GOLZAR_MASTER_READY__=true;s.onerror=()=>show("❌","بارگذاری app.js انجام نشد.");document.body.appendChild(s)}
function isDone(){try{return localStorage.getItem(D)==="1"}catch(e){return false}}
function mark(){try{localStorage.setItem(D,"1")}catch(e){}}
async function existing(c){let set=new Set(),from=0;while(true){let{data,error}=await c.from(T).select("name,lastname,piece,grave_row,grave_number").range(from,from+P-1);if(error)throw new Error("خطا در خواندن بانک موجود:\n"+(error.message||error.details||error.code));let a=data||[];a.forEach(r=>set.add(key(r)));if(a.length<P)break;from+=P}return set}
const A={name:["نام","نامشهید","نام شهید","name"],lastname:["نامخانوادگی","نام خانوادگی","نامخانوادگی شهید","نام خانوادگی شهید","lastname","family"],piece:["قطعه","قطعه شهید","piece"],grave_row:["ردیف","ردیف مزار","ردیف قبر","graverow","row"],grave_number:["شماره","شماره مزار","شماره قبر","شماره سنگ","gravenumber","number"]};
function find(rows){let z=null;for(let ri=0;ri<Math.min(30,rows.length);ri++){let n=(rows[ri]||[]).map(norm),m={};for(let f in A){let i=n.findIndex(x=>A[f].map(norm).includes(x));if(i>=0)m[f]=i}if(m.name!==undefined&&m.lastname!==undefined&&m.grave_row!==undefined&&m.grave_number!==undefined&&(!z||Object.keys(m).length>Object.keys(z.m).length))z={ri,m}}return z}
function ignore(s){return ["آمار","عکس","عکسها","تصاویر","images","photos","statistics","stat"].map(norm).includes(norm(s))}
async function excel(){if(!window.XLSX)throw Error("کتابخانه Excel بارگذاری نشده است.");upd("در حال دریافت Excel از GitHub...");let r=await fetch(E+"?v=20260822-15",{cache:"no-store"});if(!r.ok)throw Error("دریافت Excel ناموفق بود. HTTP "+r.status);let w=XLSX.read(await r.arrayBuffer(),{type:"array",raw:true,dense:true}),out=[],seen=new Set();for(let sn of w.SheetNames){if(ignore(sn))continue;let rows=XLSX.utils.sheet_to_json(w.Sheets[sn],{header:1,defval:"",raw:true,blankrows:false}),h=find(rows);if(!h)continue;for(let i=h.ri+1;i<rows.length;i++){let r=rows[i]||[],x={name:clean(r[h.m.name]),lastname:clean(r[h.m.lastname]),piece:h.m.piece!==undefined?loc(r[h.m.piece]):"",grave_row:loc(r[h.m.grave_row]),grave_number:loc(r[h.m.grave_number])};if(!x.name||!x.lastname||!x.piece||!x.grave_row||!x.grave_number)continue;x.stone_type=null;x.stage=null;x.notes=null;x.status="تأیید شده";x.created_at=new Date().toISOString();x.edited_at=null;x.edit_notes=null;let k=key(x);if(!seen.has(k)){seen.add(k);out.push(x)}}}if(!out.length)throw Error("هیچ رکورد قابل استفاده‌ای از Sheetهای قطعات پیدا نشد.");return out}
async function put(c,a,n,total,s,e){for(let t=1;t<=4;t++){upd(`در حال انتقال اولیه...\nBatch ${n} از ${total}\nرکوردهای ${s+1} تا ${e}\nتلاش ${t} از 4`);try{let{error}=await c.from(T).insert(a);if(!error)return;let m=error.message||error.details||error.code||"خطا";if(!/failed to fetch|network|timeout|abort/i.test(String(m)))throw Error(m)}catch(x){if(!/failed to fetch|network|timeout|abort/i.test(x.message||String(x)))throw Error(x.message||x)}if(t<4)await new Promise(r=>setTimeout(r,1000*t))}throw Error(`ثبت Batch ${n} پس از 4 تلاش ناموفق بود.`)}
async function sync(c,r){upd("در حال خواندن تمام رکوردهای بانک...\nصفحه‌بندی فعال است و محدودیت ۱۰۰۰ رکورد دور زده می‌شود.");let have=await existing(c),miss=r.filter(x=>!have.has(key(x)));if(!miss.length)return{existing:r.length,imported:0};let total=Math.ceil(miss.length/B);for(let s=0,n=1;s<miss.length;s+=B,n++){let e=Math.min(s+B,miss.length);await put(c,miss.slice(s,e),n,total,s,e)}return{existing:r.length-miss.length,imported:miss.length}}
async function start(){try{if(isDone()){app();return}show("⏳","در حال اتصال اولیه بانک اصلی...\nاین انتقال فقط یک بار انجام می‌شود.");if(!window.supabase||typeof window.supabase.createClient!=="function")throw Error("کتابخانه Supabase بارگذاری نشده است.");let c=window.supabase.createClient(U,K),r=await excel();upd(`Excel آماده شد.\n${r.length.toLocaleString("fa-IR")} رکورد یکتا پیدا شد.\n\nدر حال تطبیق با تمام رکوردهای بانک...`);let q=await sync(c,r);mark();show("✅",`اتصال اولیه بانک اصلی با موفقیت انجام شد.\n\nرکوردهای موجود دست‌نخورده ماندند: ${q.existing.toLocaleString("fa-IR")}\nرکوردهای جدید از Excel اضافه شد: ${q.imported.toLocaleString("fa-IR")}\n\nاین انتقال دیگر در ورودهای بعدی اجرا نمی‌شود.\nدر حال ورود به برنامه...`);setTimeout(app,900)}catch(e){console.error(e);show("❌","اتصال اولیه بانک اصلی انجام نشد.\n\n"+(e.message||String(e))+"\n\nهیچ Batch ناموفقی موفق تلقی نمی‌شود.")}}
document.addEventListener("DOMContentLoaded",start);