"use strict";

const SUPABASE_URL = "https://bafrksgdcmglahyrppfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_O5CkSuivysXJf-8hu1IUCA_izu8hWiX";
const TABLE_NAME = "martyrs";
const TOTAL_GRAVES = 26097;
const PIECES = [["17",103],["24",6100],["26",4514],["27",3177],["28",3523],["29",2743],["40",2948],["53",3092]];
const STAGES = {"ترمیمی":["طرح سنگ ارسال به واحد مرمت","سنگ مرمتی آماده","نصب سنگ مرمت شده"],"تعویضی":["طرح سنگ ارسال به واحد تعویض","سنگ تعویضی آماده","نصب سنگ تعویض شده"]};
const OLD_STAGE_ALIASES={"ارسال به واحد مرمت":"طرح سنگ ارسال به واحد مرمت","نصب مرمتی شده":"نصب سنگ مرمت شده","ارسال به واحد تعویض":"طرح سنگ ارسال به واحد تعویض","تعویضی نصب شده":"نصب سنگ تعویض شده"};
function normalizeStage(v){const x=String(v??"").trim();return OLD_STAGE_ALIASES[x]||x}
function normalizePiece(v){return String(v??"").trim().replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/\.0$/ ,"")}
function fa(v){return String(v).replace(/\d/g,d=>"۰۱۲۳۴۵۶۷۸۹"[Number(d)])}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function pct(v,d=TOTAL_GRAVES){return d?(v/d)*100:0}
async function fetchAllRows(client){const out=[],size=1000;let from=0;while(true){const {data,error}=await client.from(TABLE_NAME).select("id,piece,stone_type,stage,status").order("id",{ascending:true}).range(from,from+size-1);if(error)throw error;const batch=data||[];out.push(...batch);if(batch.length<size)break;from+=size}const seen=new Set();return out.filter(r=>{const k=String(r.id);if(seen.has(k))return false;seen.add(k);return true})}
function emptyType(type){return{total:0,completed:0,stages:Object.fromEntries(STAGES[type].map(s=>[s,0]))}}
function buildModel(rows){const m={repair:emptyType("ترمیمی"),replacement:emptyType("تعویضی"),pieces:{},tracked:0,completed:0,remaining:0,qualityWarnings:[]};for(const[piece,total]of PIECES)m.pieces[piece]={total,repair:Object.fromEntries(STAGES["ترمیمی"].map(s=>[s,0])),replacement:Object.fromEntries(STAGES["تعویضی"].map(s=>[s,0]))};for(const r of rows){const type=r?.stone_type;if(type!=="ترمیمی"&&type!=="تعویضی")continue;const stage=normalizeStage(r?.stage),target=type==="ترمیمی"?m.repair:m.replacement;target.total++;if(Object.prototype.hasOwnProperty.call(target.stages,stage))target.stages[stage]++;if(stage===STAGES[type][2])target.completed++;const p=normalizePiece(r?.piece);if(!m.pieces[p])continue;const pt=type==="ترمیمی"?m.pieces[p].repair:m.pieces[p].replacement;if(Object.prototype.hasOwnProperty.call(pt,stage))pt[stage]++}m.tracked=m.repair.total+m.replacement.total;m.completed=m.repair.completed+m.replacement.completed;m.remaining=Math.max(m.tracked-m.completed,0);if(m.repair.completed>m.repair.total)m.qualityWarnings.push("تعداد نصب مرمتی‌شده از کل ترمیمی بیشتر است.");if(m.replacement.completed>m.replacement.total)m.qualityWarnings.push("تعداد نصب تعویض‌شده از کل تعویضی بیشتر است.");for(const [piece,total] of PIECES){const x=m.pieces[piece];x.repairEligible=Object.values(x.repair).reduce((a,b)=>a+b,0);x.replacementEligible=Object.values(x.replacement).reduce((a,b)=>a+b,0);x.repairDone=x.repair[STAGES["ترمیمی"][2]]||0;x.replacementDone=x.replacement[STAGES["تعویضی"][2]]||0;x.repairRemaining=Math.max(x.repairEligible-x.repairDone,0);x.replacementRemaining=Math.max(x.replacementEligible-x.replacementDone,0);x.eligible=x.repairEligible+x.replacementEligible;x.done=x.repairDone+x.replacementDone;x.remaining=x.repairRemaining+x.replacementRemaining;x.damagePct=pct(x.eligible,total)}return m}
function bar(label,value,den,extraClass=""){const p=Math.min(pct(value,den),100);return`<div class="bar ${extraClass}"><div class="bar-head"><span>${esc(label)}</span><strong>${fa(value)} — ${fa(p.toFixed(1))}٪</strong></div><div class="track"><div class="fill" style="width:${p.toFixed(2)}%"></div></div><small class="sub">${fa(value)} از ${fa(den)}</small></div>`}
function managementTable(m){return `<div class="table-wrap"><table class="management-table"><thead><tr><th>قطعه</th><th>کل سنگ قطعه</th><th colspan="3">آمار تعویض سنگ‌ها</th><th colspan="3">آمار ترمیم سنگ‌ها</th><th>درصد آسیب قطعه</th><th>کل قابل تعویض و ترمیم</th><th>کل تعویض و ترمیم شده</th><th>کل باقی‌مانده</th></tr><tr class="subhead"><th></th><th></th><th>قابل تعویض</th><th>تعویض شده</th><th>باقی‌مانده</th><th>قابل ترمیم</th><th>ترمیم شده</th><th>باقی‌مانده</th><th></th><th></th><th></th><th></th></tr></thead><tbody>${PIECES.map(([p,total])=>{const x=m.pieces[p];return`<tr><td class="piece-name">${fa(p)}</td><td>${fa(total)}</td><td>${fa(x.replacementEligible)}</td><td>${fa(x.replacementDone)}</td><td>${fa(x.replacementRemaining)}</td><td>${fa(x.repairEligible)}</td><td>${fa(x.repairDone)}</td><td>${fa(x.repairRemaining)}</td><td><b>${fa(x.damagePct.toFixed(1))}٪</b></td><td>${fa(x.eligible)}</td><td>${fa(x.done)}</td><td>${fa(x.remaining)}</td></tr>`}).join("")}<tr class="total-row"><td>جمع کل</td><td>${fa(TOTAL_GRAVES)}</td><td>${fa(m.replacement.total)}</td><td>${fa(m.replacement.completed)}</td><td>${fa(Math.max(m.replacement.total-m.replacement.completed,0))}</td><td>${fa(m.repair.total)}</td><td>${fa(m.repair.completed)}</td><td>${fa(Math.max(m.repair.total-m.repair.completed,0))}</td><td><b>${fa(pct(m.tracked,TOTAL_GRAVES).toFixed(1))}٪</b></td><td>${fa(m.tracked)}</td><td>${fa(m.completed)}</td><td>${fa(m.remaining)}</td></tr></tbody></table></div>`}
function pieceChart(m,type){const isRepair=type==="ترمیمی";const title=isRepair?"نمودار میله‌ای ترمیمی به تفکیک قطعه":"نمودار میله‌ای تعویضی به تفکیک قطعه";const rows=PIECES.map(([p,total])=>{const x=m.pieces[p];const value=isRepair?x.repairEligible:x.replacementEligible;const done=isRepair?x.repairDone:x.replacementDone;return`<div class="chart-row"><div class="chart-label">قطعه ${fa(p)}</div><div class="chart-track"><i style="width:${Math.min(pct(value,total),100).toFixed(2)}%"></i></div><div class="chart-value">${fa(value)} <small>از ${fa(total)}</small></div><div class="chart-done">تکمیل: ${fa(done)}</div></div>`}).join("");return `<section class="card chart-card"><h2>${title}</h2><div class="chart-note">مقیاس هر قطعه نسبت به کل مزار همان قطعه است.</div>${rows}</section>`}
function render(m){const app=document.getElementById("statistics-app"),overall=pct(m.completed),tracked=pct(m.tracked),remaining=m.tracked?pct(m.remaining,m.tracked):0;const warnings=m.qualityWarnings.length?`<section class="card warning-card"><h2>هشدار کنترل داده</h2>${m.qualityWarnings.map(w=>`<div>⚠️ ${esc(w)}</div>`).join("")}</section>`:"";app.innerHTML=`<div class="page"><header class="head"><div><h1>گزارش‌های آماری</h1><p>وضعیت لحظه‌ای عملیات بهسازی سنگ مزار</p></div><button type="button" onclick="location.reload()">↻ تازه‌سازی</button></header><div class="meta">مبنای درصد از کل: <strong>${fa(TOTAL_GRAVES)}</strong> مزار در ۸ قطعه · <span class="badge">فقط خواندنی</span></div><section class="overall"><div class="card metric hero"><span>کل مزارهای مشمول آمار</span><strong>${fa(TOTAL_GRAVES)}</strong><small>مخرج فعلی درصدها؛ قابل تغییر در آینده</small></div><div class="card metric"><span>کل موارد عملیاتی ثبت‌شده</span><strong>${fa(m.tracked)}</strong><small>${fa(tracked.toFixed(1))}٪ از کل مزارها</small></div><div class="card metric"><span>تکمیل‌شده</span><strong>${fa(m.completed)}</strong><small>${fa(overall.toFixed(1))}٪ از کل مزارها</small></div><div class="card metric"><span>باقی‌مانده عملیات</span><strong>${fa(m.remaining)}</strong><small>${fa(remaining.toFixed(1))}٪ از موارد عملیاتی</small></div></section>${warnings}<section class="card"><h2>وضعیت کلی نسبت به کل مزارها</h2>${bar("ترمیم شده",m.repair.completed,TOTAL_GRAVES)}${bar("تعویض شده",m.replacement.completed,TOTAL_GRAVES)}${bar("تکمیل‌شده از کل",m.completed,TOTAL_GRAVES)}</section><section class="card"><h2>وضعیت کلی عملیات ثبت‌شده</h2>${bar("ترمیمی ثبت‌شده",m.repair.total,Math.max(m.tracked,1))}${bar("تعویضی ثبت‌شده",m.replacement.total,Math.max(m.tracked,1))}${bar("تکمیل‌شده",m.completed,Math.max(m.tracked,1))}${bar("باقی‌مانده",m.remaining,Math.max(m.tracked,1))}</section><div class="grid"><section class="card"><h2>وضعیت ترمیمی</h2><div class="stage-grid">${STAGES["ترمیمی"].map(s=>`<div class="stage"><div class="stage-title">${esc(s)}</div><strong>${fa(m.repair.stages[s])}</strong></div>`).join("")}</div></section><section class="card"><h2>وضعیت تعویضی</h2><div class="stage-grid">${STAGES["تعویضی"].map(s=>`<div class="stage"><div class="stage-title">${esc(s)}</div><strong>${fa(m.replacement.stages[s])}</strong></div>`).join("")}</div></section></div>${pieceChart(m,"ترمیمی")}${pieceChart(m,"تعویضی")}<section class="card management"><div class="section-head"><div><h2>جدول مدیریتی آمار قطعات</h2><p>قابل تعویض و قابل ترمیم از طبقه‌بندی نوع عملیات؛ تعویض‌شده و ترمیم‌شده از مرحله نهایی نصب.</p></div></div>${managementTable(m)}</section><div class="footer">این صفحه مستقل و فقط‌خواندنی است. مبنای کل فعلی ${fa(TOTAL_GRAVES)} مزار است و در صورت تغییر آمار کل قطعات، فقط مقدار مبنا و فهرست قطعات باید به‌روزرسانی شود. عناوین مراحل در خروجی با نام‌های رسمی نمایش داده می‌شوند.</div></div>`}
async function start(){const app=document.getElementById("statistics-app");try{if(!window.supabase?.createClient)throw new Error("کتابخانه اتصال به بانک بارگذاری نشده است.");const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);render(buildModel(await fetchAllRows(client)))}catch(e){console.error("Independent statistics error:",e);app.innerHTML=`<div class="error"><strong>گزارش‌های آماری بارگذاری نشد.</strong><br>${esc(e.message||String(e))}<br><br>این صفحه مستقل است و اطلاعات بانک را تغییر نمی‌دهد.</div>`}}
start();
